### ISSUE TITLE
scaling issue in the event page 

### ISSUE THREAD

**Issue by Meenakshiratnawat** [OSCode-Community/OSCodeCommunitySite#38] opened 2023-05-20 13:30 UTC
Images on the event page are not properly scaled ,I can fix it ,I am a Gssoc contributor ,kindly assign me the issue

**Comment by shramanpaul** [comment] 2023-05-20 15:30
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by akshathar-navada** [comment] 2023-05-20 15:46
> Images on the event page are not properly scaled ,I can fix it ,I am a Gssoc contributor ,kindly assign me the issue

Yes sure, go ahead! @Meenakshiratnawat

**Comment by Meenakshiratnawat** [comment] 2023-05-20 16:58
thank you  @akshathar-navada  for assigning me this issue

**Comment by akshathar-navada** [comment] 2023-05-24 04:16
> I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

Hey @shramanpaul , even u can try to resolve this issue:)

**Closed** 2023-06-02 08:03 UTC
Labels: enhancement, gssoc23
