### ISSUE TITLE
Improving the index.html 

### ISSUE THREAD

**Issue by harshsingh32** [OSCode-Community/OSCodeCommunitySite#24] opened 2023-05-20 08:08 UTC
I would like to improve the index.html of this project. I would like to add some features and make it more expressive and engaging for the users.

**Comment by harshsingh32** [comment] 2023-05-20 08:08
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by adityavpawar** [comment] 2023-05-20 08:33
I would like to work on this issue because my skillsets are related to this technology stack, can you please assign this issue to me

**Comment by Anushka20365** [comment] 2023-05-20 09:26
Hello @akshitagupta15june ma'am ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by Anushka20365** [comment] 2023-05-20 09:27
Hello ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by Developer-Swati** [comment] 2023-05-20 09:52
Hello, I am Swati . I am new to the open source . I have basic knowledge of HTML, CSS, JS . And I want to contribute in this project .Please assign it to me.

**Comment by akshathar-navada** [comment] 2023-05-20 15:20
Hello buddies!!, thanks for stepping up. As this is a Open source project you can pull a request at any time we will review it and  would be happy to merge it
Thank you! @harshsingh32 @adityavpawar @Anushka20365 @Developer-Swati

**Comment by shramanpaul** [comment] 2023-05-20 15:27
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by akshathar-navada** [comment] 2023-05-22 03:54
> I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

Yes sure, go ahead!!

**Closed** 2023-05-24 04:02 UTC
