### ISSUE TITLE
Contact Us Section

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#42] opened 2023-05-20 14:01 UTC
- Message button is antiquated...
![mu](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/b4316b71-f153-45cb-bb3e-117942d6ba91)
**Please assign me this issue - I want to contribute as a part of GSSoC'23.** 
I've solved this issue !

**Comment by shramanpaul** [comment] 2023-05-20 15:29
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by peb-peb** [comment] 2023-05-20 15:48
@AdityaLahane-2003 Go ahead and submit a pull request, we would be happy to merge it!

**Closed** 2023-05-20 15:49 UTC
