### ISSUE TITLE
Improving navbar

### ISSUE THREAD

**Issue by babitarit** [OSCode-Community/OSCodeCommunitySite#27] opened 2023-05-20 10:41 UTC
![Screenshot (85)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/118760765/7129bd35-2107-40c6-ba3a-fa44c11d3ab5)

due to background color of navbar its hiding the content when we scroll down 
I can improve it please assign this to me.

**Comment by Sharad-Pratap** [comment] 2023-05-20 11:05
Please assign this project to me, i will fix this.

**Comment by akshathar-navada** [comment] 2023-05-20 15:24
> ![Screenshot (85)](https://user-images.githubusercontent.com/118760765/239682646-7129bd35-2107-40c6-ba3a-fa44c11d3ab5.png)
> 
> due to background color of navbar its hiding the content when we scroll down I can improve it please assign this to me.

Yes sure, go ahead! @babitarit

**Comment by akshathar-navada** [comment] 2023-05-20 15:25
> Please assign this project to me, i will fix this.

@Sharad-Pratap , As this is a open source project, you can pull request at any time, we will be happy to review and merge it 🙂

**Comment by shramanpaul** [comment] 2023-05-20 15:34
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by babitarit** [comment] 2023-05-20 16:02
please assign it to me so that i can start working

**Comment by babitarit** [comment] 2023-05-20 16:27
thanks for assigning this issue i had raise PR please review it

**Closed** 2023-05-20 17:03 UTC
