### ISSUE TITLE
Ui Fixes 

### ISSUE THREAD

**Issue by SubhamB2003** [OSCode-Community/OSCodeCommunitySite#31] opened 2023-05-20 11:33 UTC
The navbar elements are not looking good whenever I hover on it and also the sidebar is too much normal.

I am really interested in working on this issue.
Please assign it to me under GSSOC 23.

**Comment by akshathar-navada** [comment] 2023-05-20 15:30
Yes sure, go ahead!! @SubhamB2003

**Comment by shramanpaul** [comment] 2023-05-20 15:33
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by SubhamB2003** [comment] 2023-05-20 15:45
> Yes sure, go ahead!! @SubhamB2003

Hey, @akshathar-navada can I add a blur effect on the navbar?
You can show the example I add how its looks
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/a19676f0-ddaf-4520-a066-1e11a9b47281)

**Comment by akshathar-navada** [comment] 2023-05-20 16:36
@SubhamB2003 Can u please add the screenshot of home and about section with too with the blurred navbar ...so that I can review it...

**Comment by SubhamB2003** [comment] 2023-05-20 16:44
> @SubhamB2003 Can u please add the screenshot of home and about section with too with the blurred navbar ...so that I can review it...

Sure
Home Section
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/5611cc23-4ca2-4887-a479-f495dcb2a4e9)


About Section
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/73790392-7574-4e5e-9be0-444fa56b938f)

**Comment by akshathar-navada** [comment] 2023-05-20 16:49
> > @SubhamB2003 Can u please add the screenshot of home and about section with too with the blurred navbar ...so that I can review it...
> 
> Sure Home Section ![image](https://user-images.githubusercontent.com/94003231/239699352-5611cc23-4ca2-4887-a479-f495dcb2a4e9.png)
> 
> About Section ![image](https://user-images.githubusercontent.com/94003231/239699314-73790392-7574-4e5e-9be0-444fa56b938f.png)
> 
> Can you please add the GSSOC 23 label🙂

We have merged your PR, will be adding the GSSOC 23 label soon!
Thank you!! @SubhamB2003

**Closed** 2023-05-20 16:49 UTC

**Comment by SubhamB2003** [comment] 2023-05-20 16:54
> > > @SubhamB2003 Can u please add the screenshot of home and about section with too with the blurred navbar ...so that I can review it...
> > 
> > 
> > Sure Home Section ![image](https://user-images.githubusercontent.com/94003231/239699352-5611cc23-4ca2-4887-a479-f495dcb2a4e9.png)
> > About Section ![image](https://user-images.githubusercontent.com/94003231/239699314-73790392-7574-4e5e-9be0-444fa56b938f.png)
> > Can you please add the GSSOC 23 label🙂
> 
> We have merged your PR, will be adding the GSSOC 23 label soon! Thank you!! @SubhamB2003

Thank you🙂
