### ISSUE TITLE
Make footer static

### ISSUE THREAD

**Issue by vaidehidangi23** [OSCode-Community/OSCodeCommunitySite#32] opened 2023-05-20 11:35 UTC
For example on the blog's page, these icons should be in the footer, so if we make the footer static then this will be included automatically on every page 
![gssoc2](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/62616333/122b98cb-b39b-43c5-ac16-a00258a31900)

**Comment by ARGHYADIPROY** [comment] 2023-05-20 13:09
The footer is not static. The social media links are appearing upper position on the website. I will make this footer static.
![SharedScreenshot](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93476373/55d56e18-1c0e-48c5-8e31-69a324bbc354)
Please assign me this issue , I want to work on this issue under the GSSoC'23.

**Comment by shramanpaul** [comment] 2023-05-20 15:32
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me

**Comment by akshathar-navada** [comment] 2023-05-20 15:39
This is under progress, we are currently creating blogs in hashnode. So, we will be closing this issue as of now.
Thanks for stepping up! and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you!! @ARGHYADIPROY @shramanpaul @vaidehidangi23

**Closed** 2023-05-20 15:45 UTC
