### ISSUE TITLE
Transparency Level set in Navbar

### ISSUE THREAD

**Issue by Geeta259** [OSCode-Community/OSCodeCommunitySite#34] opened 2023-05-20 12:23 UTC
while navigate up and down background content visible also in navbar section .
I want  to resolve this issue and want to contribute under GSSOC'23.

**Comment by ARGHYADIPROY** [comment] 2023-05-20 13:04
I will make the navbar background transparent when we are scrolling up & down.
![SharedScreenshot](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93476373/a25d759c-6f13-4060-90cb-9175c1a453aa)
I will make this navbar transparent
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by shramanpaul** [comment] 2023-05-20 15:30
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by akshathar-navada** [comment] 2023-05-20 15:41
Hello buddies! thanks for stepping up yea try to fix the issue and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you! @Geeta259 @ARGHYADIPROY @shramanpaul

**Comment by ARGHYADIPROY** [comment] 2023-05-20 15:43
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by ARGHYADIPROY** [comment] 2023-05-21 12:33
Please give it "GSSoC'23" label.

**Comment by akshathar-navada** [comment] 2023-05-21 13:54
@ARGHYADIPROY we prefer the existing one, pls  check out the current navbar in mobile size. 
Thank you for stepping up, if there is any other issue which u want to contribute, pls go ahead!!

**Closed by akshathar-navada** 2023-05-21 13:54 UTC

**Comment by ARGHYADIPROY** [comment] 2023-05-21 14:44
Thanks. Please assign me other issues I would love to do that.
