### ISSUE TITLE
Home Section need some Improvement 

### ISSUE THREAD

**Issue by 9520prashant** [OSCode-Community/OSCodeCommunitySite#47] opened 2023-05-20 15:02 UTC
Home Section looks like wired in terms of UI i think it need some improvement. Hey @FuryACE007 @vinitvijal @ng169 @akashgreninja @rashi2911 assign me this so that I will improve the Home section.
![Screenshot (226)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/99237795/5423468f-d7c6-4daf-b63b-6fbcd45fd84e)

**Comment by peb-peb** [comment] 2023-05-20 15:17
Assigning @9520prashant  

Could you please show a proposed UI for the Home Screen? We can move forward from there.

**Comment by shramanpaul** [comment] 2023-05-20 15:29
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by 9520prashant** [comment] 2023-05-20 15:29
> Assigning @9520prashant
> 
> Could you please show a proposed UI for the Home Screen? We can move forward from there.

Yes I working on it will share soon

**Comment by Amankumarharsh** [comment] 2023-05-20 15:32
@peb-peb  hello sir,
I'm a beginner so unable to find new issues pls assign me some issues

**Comment by peb-peb** [comment] 2023-05-20 15:50
@Amankumarharsh I'll add some beginner-friendly issues soon! Be on a lookout for them.

**Comment by 9520prashant** [comment] 2023-05-20 15:55
@Amankumarharsh @shramanpaul Yes Please have some patience.

**Comment by 9520prashant** [comment] 2023-05-20 18:52
hey @peb-peb I faced issue in order to set-up this project locally can you help me to solve this issue
![Screenshot (227)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/99237795/d104bd60-4b3c-4a79-928f-565d7dd6230a)

**Comment by 9520prashant** [comment] 2023-05-21 09:28
Hey @peb-peb I have made this Design for Home Section. Kindly Check It.

[Home Section Design](https://www.figma.com/file/I6q8lLZ7q6zPQLFFe2wF4l/Untitled?type=design&node-id=1%3A18&t=AUP90iFjy90P7KG0-1)

**Comment by akshathar-navada** [comment] 2023-05-22 04:05
> hey @peb-peb I faced issue in order to set-up this project locally can you help me to solve this issue
> 
> ![Screenshot (227)](https://user-images.githubusercontent.com/99237795/239704799-d104bd60-4b3c-4a79-928f-565d7dd6230a.png)

Hey @9520prashant , please pull the repo properly, has there will be many PR and we will be merging it also, may be it might be becos of that. Try forking the repo again ,by deleting the existing one. If u r still facing any issue in setting , please let us know:)

**Comment by akshathar-navada** [comment] 2023-05-22 04:08
@9520prashant , I'm not able to see anything in the link which u have provided. I mean there is blank section. It would be better if u add a screenshot of it, so that I can review it easily!!
Thank you.

**Comment by 9520prashant** [comment] 2023-05-22 04:08
Hey I haven't create any PR yet

**Comment by 9520prashant** [comment] 2023-05-22 06:42
Hey @akshathar-navada sorry for that I have attached the Screen Shot please will let me know if it is ok.

![Screenshot (240)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/99237795/3addaa7f-77d4-4b2f-a1cc-c03b5d28aac6)

**Comment by 9520prashant** [comment] 2023-05-22 06:43
Hey @akshathar-navada I tried but still I am facing this issue again and again. How can i deal with that issue.

**Closed** 2023-05-24 04:17 UTC
Labels: enhancement, UI
