### ISSUE TITLE
Improve Our Sponsors and partners Section

### ISSUE THREAD

**Issue by shreya26-bit** [OSCode-Community/OSCodeCommunitySite#43] opened 2023-05-20 14:21 UTC
Arrow cursor does not change to a hand cursor, when clicking on sponsors. I wants to solve this issue .please assigned this issue to me

**Comment by shramanpaul** [comment] 2023-05-20 15:31
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by peb-peb** [comment] 2023-05-20 15:48
Go ahead and submit a pull request, we would be happy to merge it! @shreya26-bit

**Closed** 2023-05-20 19:39 UTC
