### ISSUE TITLE
College Chapter Section

### ISSUE THREAD

**Issue by Rohit-osc** [OSCode-Community/OSCodeCommunitySite#33] opened 2023-05-20 12:12 UTC
In the college chapter section if we click on the any college name, website do not redirect us to the respective college website.
Please assign this work to me I will fix this bug.

**Comment by ARGHYADIPROY** [comment] 2023-05-20 13:00
I want to work on this issue under the GSSoC'23. In the college chapter section, if we click on any college name, the website doesn't go to the respective college website.
Please assign this work to me I will fix this bug. Please give me this work.

**Comment by shramanpaul** [comment] 2023-05-20 15:34
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by akshathar-navada** [comment] 2023-05-20 15:36
This is under progress, we are currently creating individual pages to each college. So, we will be closing this issue as of now.
Thanks for stepping up! and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you!! @ARGHYADIPROY @shramanpaul @Rohit-osc

**Closed by akshathar-navada** 2023-05-20 15:36 UTC

**Comment by akshathar-navada** [comment] 2023-05-20 15:37
This is under progress, we are currently creating individual pages to each college. So, we will be closing this issue as of now.
Thanks for stepping up! and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you!! @ARGHYADIPROY @shramanpaul @Rohit-osc
